controller:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  left_front_wheel_joint_controller:
    type: velocity_controllers/joint_velocity_controller
    joint: left_front_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_front_wheel_joint_controller:
    type: velocity_controllers/joint_velocity_controller
    joint: right_front_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_back_wheel_joint_controller:
    type: velocity_controllers/joint_velocity_controller
    joint: left_back_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_back_wheel_joint_controller:
    type: velocity_controllers/joint_velocity_controller
    joint: right_back_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}