Controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController
    left_front_wheel_joint:
      joint: front_left_joint_


    right_front_wheel_joint:
      joint: front_right_joint_


    left_back_wheel_joint:
      joint: back_left_joint_


    right_back_wheel_joint:
      joint: back_right_joint_
      
    vel_mode: odom

    pid: {p: 100.0, i: 0.01, d: 10.0}


  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

